version: "3.9"
services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - OPEN_AI_API_KEY=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
      - NEWS_API_KEY=xQxMrXS35s6ydh24TfOBoMYVLsIG2JkwlQG0wB2R