server:
  port: 8080

spring:
  application:
    name: news
###########################
#### DATABASE SETTINGS ####
###########################
  datasource:
    url: jdbc:h2:mem:myNewsDB
    username: sa
    password: password
    driverClassName: org.h2.Driver
###########################
###### JPA SETTINGS #######
###########################
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
    open-in-view: false
###########################
###### LOGGING SETTINGS #####
###########################
logging:
  level:
    root: INFO
    feign.client: INFO
    org.springframework.web: INFO
###########################
###### API SERVICES ##########
###########################
api-service:
  the-news-api:
    api_token: xQxMrXS35s6ydh24TfOBoMYVLsIG2JkwlQG0wB2R
    url: https://api.thenewsapi.com/v1/news
