server:
  port: 8080

spring:
  application:
    name: news
###########################
#### DATABASE SETTINGS ####
###########################

###########################
###### LOGGING SETTINGS #####
###########################
logging:
  level:
    root: INFO
    feign.client: INFO
    org.springframework.web: INFO
###########################
###### API SERVICES ##########
###########################
api-service:
  the-news-api:
    api_token: xQxMrXS35s6ydh24TfOBoMYVLsIG2JkwlQG0wB2R
    url: https://api.thenewsapi.com/v1/news
