server:
  port: 8080

spring:
  application:
    name: news
  ###########################
  #### OPEN API SETTINGS #######
  ###########################
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4-turbo
###########################
###### LOGGING SETTINGS #####
###########################
logging:
  level:
    root: INFO
    feign.client: INFO
    org.springframework.web: INFO
###########################
###### API SERVICES ##########
###########################
api-service:
  the-news-api:
    api_token: ${NEWS_API_KEY}
    url: https://api.thenewsapi.com/v1/news
