server:
  port: 8080

spring:
  application:
    name: news
  ###########################
  #### OPEN API SETTINGS #######
  ###########################
  ai:
    openai:
      #api-key: ${OPEN_AI_API_KEY}
      api-key: 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
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4-turbo
###########################
###### LOGGING SETTINGS #####
###########################
logging:
  level:
    root: INFO
    feign.client: INFO
    org.springframework.web: INFO
###########################
###### API SERVICES ##########
###########################
api-service:
  the-news-api:
    api_token: xQxMrXS35s6ydh24TfOBoMYVLsIG2JkwlQG0wB2R
    url: https://api.thenewsapi.com/v1/news
